WHITESPACE           = _{ " " | "\t" | "\r" | "\n" }
string               = @{ "\"" ~ (!"\"" ~ ANY)* ~ "\"" }
float                = @{ ((ASCII_DIGIT)+ ~ ("."))? ~ (ASCII_DIGIT)+ }
boolean              =  { "true" | "false" }
symbol               = @{ (ASCII_ALPHA | "_")+ }
value                =  { string | float | boolean }
expression           =  { value | symbol | function_call }
function_call        =  { symbol ~ "(" ~ (expression ~ ("," ~ expression)*)? ~ ")" }
variable_declaration =  { "val" ~ symbol ~ "=" ~ expression ~ NEWLINE? }
main                 =  {
    SOI ~ (variable_declaration | function_call)* ~ EOI
}
